export const PERSONAGENS_PAGE_PATH = '/v1/public/characters/'
export const PERSONAGEM_PAGE_PATH = '/v1/public/characters/:id'
export const COMICS_PAGE_PATH = '/v1/public/characters/:id/comics'
export const EVENTS_PAGE_PATH = '/v1/public/characters/:id/events'
export const SERIES_PAGE_PATH = '/v1/public/characters/:id/series'
export const STORIES_PAGE_PATH = '/v1/public/characters/:id/stories'